name: "myapp"
host: "localhost"
port: 8080
log:
  srv_name: "myapp"
  level: "info"
  format: "json"
  output: "file"
  path: "./logs"
  filename: "myapp"
  max_age: 7
  max_size: 10

mysql:
  master:
    - "root:root@tcp(localhost:3306)/openapi?charset=utf8mb4&parseTime=true&loc=Local"
  slave:
    - "root:root@tcp(localhost:3306)/openapi?charset=utf8mb4&parseTime=true&loc=Local"
    - "root:root@tcp(localhost:3306)/openapi?charset=utf8mb4&parseTime=true&loc=Local"
  max_idle_conns: 5
  max_open_conns: 50
  conn_max_lifetime: 3600
  conn_max_idle_time: 1800

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  prefix: "myapp"